source ENV['GEM_SOURCE'] || 'https://rubygems.org'

gem 'concurrent-ruby'
gem 'test-kitchen'
gem 'kitchen-digitalocean'
gem 'chef'
gem 'chef-zero'
gem 'inspec'
gem 'kitchen-inspec'
gem 'activesupport'
gem 'berksfile'
gem 'json'
