---
version: "3"
services:
  vault:
    image: vault
    entrypoint:
      - vault
      - server
      - -config=/vault/config/vault.conf
    build: ./
    hostname: vault
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    networks:
      rehab.earth:
        aliases:
          - vault.rehab.earth

networks:
  rehab.earth:
    external:
      name: rehab.earth
