---
version: "2"
services:
  vault:
    image: vault
    entrypoint:
      - vault
      - server
      - -config=/vault/config/vault.conf
    build: ./
    hostname: vault
    cap_add:
      - IPC_LOCK
    ports:
      - "127.0.0.1:8200:8200"
    networks:
      rehab.earth:
        aliases:
          - vault.rehab.earth
        # Temporary static IP address until Docker Swarm or similar knows how to resolve consul cluster
        ipv4_address: 172.100.0.5

networks:
  rehab.earth:
    external:
      name: rehab.earth
