resources:
- name: resource-rehab-earth
  type: git
  source:
    uri: https://github.com/Klazomenai/rehab.earth.git

jobs:
- name: master-rehab-earth
  plan:
  - get: resource-rehab-earth
    trigger: true
  - task: tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: sideci/ubuntu14.04-ruby-bundler}
      inputs:
        - name: resource-rehab-earth
      run:
        dir: resource-rehab-earth
        path: scripts/run_tests.sh
