name 'mailcow'
maintainer 'Klazomenai'
maintainer_email 'klazomenai@rehab.earth'
license 'all_rights'
description 'Installs/Configures MailCow Droplet'
long_description 'Installs/Configures MailCow Droplet'
version '0.1.0'

depends 'firewall', '~> 2.5'
depends 'apt'
depends 'apt-docker'
depends 'docker', '~> 2.0'
