---
version: "3"
services:
  consul1:
    command: consul agent -data-dir=/consul/data -config-dir=/consul/config -dev -client 0.0.0.0 -bind 0.0.0.0 -server -bootstrap
    image: consul
    hostname: consul1
    ports:
      - "127.0.0.1:8501:8500"
    networks:
      rehab.earth:
        aliases:
          - consul1.rehab.earth

  consul2:
    command: consul agent -data-dir=/consul/data -config-dir=/consul/config -dev -client 0.0.0.0 -bind 0.0.0.0 -server -rejoin -retry-join=consul1
    image: consul
    hostname: consul2
    depends_on:
      - consul1
    ports:
      - "127.0.0.1:8502:8500"
    networks:
      rehab.earth:
        aliases:
          - consul2.rehab.earth

  consul3:
    command: consul agent -data-dir=/consul/data -config-dir=/consul/config -dev -client 0.0.0.0 -bind 0.0.0.0 -server -rejoin -retry-join=consul1
    image: consul
    hostname: consul3
    depends_on:
      - consul1
    ports:
      - "127.0.0.1:8503:8500"
    networks:
      rehab.earth:
        aliases:
          - consul3.rehab.earth

networks:
  rehab.earth:
    external:
      name: rehab.earth
