---
version: "2"
services:
  consul1:
    command: consul agent -data-dir=/consul/data -config-dir=/consul/config -dev -client 0.0.0.0 -bind 0.0.0.0 -server -bootstrap
    image: consul
    hostname: consul1
    ports:
      - "127.0.0.1:8301:8300"
      - "127.0.0.1:8401:8400"
      - "127.0.0.1:8501:8500"
      - "127.0.0.1:8601:8600"
      - "127.0.0.1:9001:9001"

  consul2:
    command: consul agent -data-dir=/consul/data -config-dir=/consul/config -dev -client 0.0.0.0 -bind 0.0.0.0 -server -rejoin -retry-join=consul1
    image: consul
    hostname: consul2
    depends_on:
      - consul1
    ports:
      - "127.0.0.1:8302:8300"
      - "127.0.0.1:8402:8400"
      - "127.0.0.1:8502:8500"
      - "127.0.0.1:8602:8600"
      - "127.0.0.1:9002:9001"

  consul3:
    command: consul agent -data-dir=/consul/data -config-dir=/consul/config -dev -client 0.0.0.0 -bind 0.0.0.0 -server -rejoin -retry-join=consul1
    image: consul
    hostname: consul3
    depends_on:
      - consul1
    ports:
      - "127.0.0.1:8303:8300"
      - "127.0.0.1:8403:8400"
      - "127.0.0.1:8503:8500"
      - "127.0.0.1:8603:8600"
      - "127.0.0.1:9003:9001"
