---
version: "3"
services:
  consul1:
    command: consul agent -data-dir=/consul/data -config-dir=/consul/config -dev -client 0.0.0.0 -bind 0.0.0.0 -server -bootstrap
    image: consul
    hostname: consul1
    ports:
      - "8301:8300"
      - "8401:8400"
      - "8501:8500"
      - "8601:8600"
      - "9001:9001"
    networks:
      rehab.earth:
        aliases:
          - consul1.rehab.earth

  consul2:
    command: consul agent -data-dir=/consul/data -config-dir=/consul/config -dev -client 0.0.0.0 -bind 0.0.0.0 -server -rejoin -retry-join=consul1
    image: consul
    hostname: consul2
    depends_on:
      - consul1
    ports:
      - "8302:8300"
      - "8402:8400"
      - "8502:8500"
      - "8602:8600"
      - "9002:9001"
    networks:
      rehab.earth:
        aliases:
          - consul2.rehab.earth

  consul3:
    command: consul agent -data-dir=/consul/data -config-dir=/consul/config -dev -client 0.0.0.0 -bind 0.0.0.0 -server -rejoin -retry-join=consul1
    image: consul
    hostname: consul3
    depends_on:
      - consul1
    ports:
      - "8303:8300"
      - "8403:8400"
      - "8503:8500"
      - "8603:8600"
      - "9003:9001"
    networks:
      rehab.earth:
        aliases:
          - consul3.rehab.earth

networks:
  rehab.earth:
    external:
      name: rehab.earth
