---
version: "2"
services:
  concourse-db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: changeme
      PGDATA: /database
    networks:
      rehab.earth:
        aliases:
          - concourse-db.rehab.earth
        # Temporary static IP address until Docker Swarm or similar knows how to resolve consul cluster
        ipv4_address: 172.100.0.6

  concourse-web:
    image: klazomenai/concourse.rehab.earth
    links: [concourse-db]
    command: web
    ports: ["127.0.0.1:8080:8080"]
    volumes: ["./keys/web:/concourse-keys"]
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: concourse
      CONCOURSE_BASIC_AUTH_PASSWORD: changeme
      CONCOURSE_EXTERNAL_URL: "${CONCOURSE_EXTERNAL_URL}"
      CONCOURSE_POSTGRES_DATA_SOURCE: |-
        postgres://concourse:changeme@concourse-db:5432/concourse?sslmode=disable
    networks:
      rehab.earth:
        aliases:
          - concourse-web.rehab.earth
        # Temporary static IP address until Docker Swarm or similar knows how to resolve consul cluster
        ipv4_address: 172.100.0.7

  concourse-worker:
    image: klazomenai/concourse.rehab.earth
    privileged: true
    links: [concourse-web]
    command: worker
    volumes:
      - ./keys/worker:/concourse-keys
      - /tmp/worker-state:/worker-state
    environment:
      CONCOURSE_TSA_HOST: concourse-web
      CONCOURSE_GARDEN_DNS_SERVER: 8.8.8.8
      # The branch is required so we can build off other things than just master. The worker should
      # really be capable to call Concourse on its own and not depend on this.
      PROJECT_BRANCH: "${TF_VAR_project_branch}"
      # Required to be able to build things through DigitalOcean. The worker should ideally be Vault
      # aware and be able to query the token itself. This method is not great and has limitations.
      DO_PAT: "${DO_PAT}"
    networks:
      rehab.earth:
        aliases:
          - concourse-worker.rehab.earth
        # Temporary static IP address until Docker Swarm or similar knows how to resolve consul cluster
        ipv4_address: 172.100.0.8

networks:
  rehab.earth:
    external:
      name: rehab.earth
